alias ..='cd ..'
alias df='df -kh'
alias du='du -kh'
alias grep='grep --color=auto'
alias h='history'
alias l='ls -A1'
alias la='ls -AlhG'
alias ll='ls -lhG'
alias ls='ls -G'
alias openports='sudo lsof -i -P | grep -i "listen"'
alias tree='tree -aC'
