#!/usr/bin/env bash
set -e

cd "$(dirname "$0")/.."
export DOTFILES_DIR=$(pwd)

(exec "$DOTFILES_DIR/script/uninstall")

echo "==> Installing dotfiles"
for source in src/*; do
  target="$HOME/.$(basename "$source")"
  ln -sFv "$DOTFILES_DIR/$source" "$target"
done

echo "==> Installing lib"
ln -sFv "$DOTFILES_DIR/lib" "$HOME/.lib"

# Link binfiles
echo "==> Installing bin"
BIN_DIR="$HOME/bin"
mkdir -pv $BIN_DIR

echo "==> Linking bins"
for source in "$HOME/.bin/"*; do
  target="$BIN_DIR/$(basename "$source")"
  ln -sFv "$source" "$target"
done

for installer in script/install-*.sh; do
  source $installer
done
