#!/usr/bin/env bash
set -e

cd "$(dirname "$0")/.."
DOTFILES_DIR=$(pwd)

(exec "$DOTFILES_DIR/script/uninstall")

for source in *; do
  target="$HOME/.$(basename "$source")"
  ln -sFv "$DOTFILES_DIR/$source" "$target"
done

# Link binfiles
BIN_DIR="$HOME/bin"
mkdir -pv $BIN_DIR

for source in "$HOME/.bin/"*; do
  target="$BIN_DIR/$(basename "$source")"
  ln -sFv "$source" "$target"
done

source "$DOTFILES_DIR/script/install-user-bins.sh"
source "$DOTFILES_DIR/script/install-launch-agents.sh"
source "$DOTFILES_DIR/script/install-services.sh"
