#!/usr/bin/env bash
set -e

cd "$(dirname "$0")/.."
DOTFILES_DIR=$(pwd)

for source in *; do
  target="$HOME/.$(basename "$source")"
  if [[ ! -L "$target" ]]; then
    ln -sv "$DOTFILES_DIR/$source" "$target"
  fi
done

# Link binfiles
BIN_DIR="$HOME/bin"
mkdir -pv $BIN_DIR

for source in "$HOME/.bin/"*; do
  target="$BIN_DIR/$(basename "$source")"
  if [[ ! -L "$target" ]]; then
    ln -sv "$source" "$target"
  fi
done

source "$DOTFILES_DIR/script/install-user-bins.sh"
