#!/bin/bash
set -e

cd "$(dirname "$0")/.."
DOTFILES_DIR=$(pwd)

for source in *; do
  target="$HOME/.$(basename "$source")"
  if [ -L "$target" ]; then
    if readlink "$target" | grep -q "$DOTFILES_DIR"; then
      rm -v "$target"
    fi
  fi
done
